### ISSUE TITLE
Dragapult

### ISSUE THREAD

**Issue by hexbyt3** [MewTracker/sv-research#11]
Hey there!

im having a hard time finding any dragapult raid seeds. Is there something I’m missing?

**Comment by MewTracker** [comment]
It's a Violet exclusive (found in 4 and 5 star raids).

**Comment by hexbyt3** [comment]
Ohhh snap I haven’t tried yet but I’m guessing I can’t put a violet seed in a scarlet game right?

**Comment by MewTracker** [comment]
You will get a different Pokémon. You can check that via seed viewer feature.
