### ISSUE TITLE
RaidCalc 3.7.0 Executable not responding

### ISSUE THREAD

**Issue by xk3ll3rk1nd** [MewTracker/sv-research#12]
Whenever I use the Seed Viewer, regardless of how many characters/numbers I'm typing it will immediately crash/stop responding until I force close the application. Any solution or am I just dumb lol.

**Comment by MewTracker** [comment]
Please provide a more detailed description of the problem, so I can try to reproduce it. List all the settings of seed viewer before you cause application to hang.

**Comment by xk3ll3rk1nd** [comment]
0. Opening the Program - RaidCalc v3.7.0 (with or without admin permissions doesnt change anything)

* I also use/d Seeds from your Thread at ProjectPokemon.org

>> e.g. https://github.com/MewTracker/sv-research/blob/master/Seeds/herba_seeds_scarlet.txt


1. Tools ~> Seed Viewer 

Raid Parameter: 
- Game: Scarlet/Violet
- Event: None
- Raid Type: 6-7 Stars
- Story Progess: 6* unlocked 
- Raid boost: 0
- Seed: ***

*** Immediately upon entering any information like just '1' or a whole seed like '13C67392' the application stops responding until force close. 

>> No other changes were made.

(2.Doing the same just with other information will result in a loop of the same problem over and over again)

**Comment by MewTracker** [comment]
No reproduction for this. The only thing that comes to my mind is some sort of memory corruption caused by wrong redistributable version in your system. Try to install the newest one: https://aka.ms/vs/17/release/vc_redist.x64.exe
