### ISSUE TITLE
Adding rewards to csv export

### ISSUE THREAD

**Issue by hexbyt3** [MewTracker/sv-research#14]
Hello!

is there any way you can include the rewards to be in the csv export? 

Thanks for your amazing work!  <3

**Comment by MewTracker** [comment]
How would you like to see that implemented? Extra column for every reward from selected ones?

**Comment by hexbyt3** [comment]
Thanks for commenting back!  I am making a discord bot that uses the exported data from raidcalc to return a result based on what the user chooses. I have also made a website based version:  https://mewtwoscloning.com/raid-seed-generator

I’m not sure the best way to implement it in raidcalc, but if I had a way to export that the rewards are 

{

“Rewards”: “Rare Candy x2, Ability Patch x1, etc”

}
In my json data that is probably how I would do it. I convert the csv to json

**Comment by MewTracker** [comment]
I added option to include rewards along with JSON support :)

**Comment by hexbyt3** [comment]
Let’s gooooooo!!!!!!! You rock!!!

**Comment by bdawg1989** [comment]
> 

I can't get it to build without errors.  Could you please update the release for it <3

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'QDialog': No such file or directory	RaidCalc	C:\Users\*\Desktop\sv-research-master\RaidCalc\AboutDialog.h	3	
Error	C1083	Cannot open include file: 'QtGlobal': No such file or directory	RaidCalc	C:\Users\*\Desktop\sv-research-master\RaidCalc\Benchmarks.cpp	1	
Error	C1083	Cannot open include file: 'QDialog': No such file or directory	RaidCalc	C:\Users\*\Desktop\sv-research-master\RaidCalc\EncounterDatabaseDialog.h	3	
Error	C1083	Cannot open include file: 'QMessageBox': No such file or directory	RaidCalc	C:\Users\*\Desktop\sv-research-master\RaidCalc\ExportDialog.cpp	1	
Error	C1083	Cannot open include file: 'QDialog': No such file or directory	RaidCalc	C:\Users\*\Desktop\sv-research-master\RaidCalc\ItemFilterDialog.h	3	
Error	C1083	Cannot open include file: 'QString': No such file or directory	RaidCalc	C:\Users\*\Desktop\sv-research-master\RaidCalc\Utils.h	3	
Error	C1083	Cannot open include file: 'QDialog': No such file or directory	RaidCalc	C:\Users\*\Desktop\sv-research-master\RaidCalc\SeedViewerDialog.h	3	
Error	C1083	Cannot open include file: 'QHeaderView': No such file or directory	RaidCalc	C:\Users\*\Desktop\sv-research-master\RaidCalc\SettingsDialog.cpp	1	
Error	C1083	Cannot open include file: 'QFile': No such file or directory	RaidCalc	C:\Users\*\Desktop\sv-research-master\RaidCalc\Utils.cpp	1	
Error	C1083	Cannot open include file: 'QMessageBox': No such file or directory	RaidCalc	C:\Users\*\Desktop\sv-research-master\RaidCalc\RaidCalc.cpp	1	
Error	C1083	Cannot open include file: 'QtWidgets/QMainWindow': No such file or directory	RaidCalc	C:\Users\*\Desktop\sv-research-master\RaidCalc\RaidCalc.h	3
