### ISSUE TITLE
Suggestion for more filters 

### ISSUE THREAD

**Issue by nlqhs** [MewTracker/sv-research#17]
I was wondering if it's possible to add more filters such as XOR (=0 or any) and/or EC

**Comment by MewTracker** [comment]
What is the rationale for adding those? XOR=0 has very little usage (square shiny in SWSH) but I completely don't see any reason for EC filtering.

**Comment by nlqhs** [comment]
ah i thought EC is for rare forms (Dunsparce, Tandemaus). I might be wrong.

**Comment by MewTracker** [comment]
> ah i thought EC is for rare forms (Dunsparce, Tandemaus). I might be wrong.

RaidCalc already supports filtering for rare forms though.

**Comment by nlqhs** [comment]
Ah thank you. I was not aware. I will check it out. I assume that rare form filter only works with evolved seed instead of pre-evolve seed
