### ISSUE TITLE
RaidCalc parameters question

### ISSUE THREAD

**Issue by Crobat169** [MewTracker/sv-research#18]
Thanks for your work, Sorry to bother you that I would like to know what does Threads(1~7) mean in the Basic Parameters set?

**Comment by MewTracker** [comment]
This setting controls how many hardware threads (CPU cores) will be used to parallelize the search. More threads == more CPU utilization == faster search (not always but it's true in general).

**Comment by Crobat169** [comment]
I’ve checked different options with Threads and got the same results only with noticeable reaction speed difference of showing results so that’s the answer, thank you.
