### ISSUE TITLE
Size parameters

### ISSUE THREAD

**Issue by maxwell-zeus** [MewTracker/sv-research#19]
How should I set the 3 size parameters in order to obtain a jumbo or mini mark?

**Comment by MewTracker** [comment]
https://www.nintendolife.com/guides/pokemon-scarlet-and-violet-what-are-marks-and-ribbons-how-to-give-your-pokemon-a-title#mark-types-and-effects

**Comment by maxwell-zeus** [comment]
So if i will search for humungo, should i set the scale to 255-255 and tiny 0-0? Ignore any parameter set to height and weight?

**Comment by MewTracker** [comment]
That should do the trick. This is further confirmed by Bulbapedia: https://bulbapedia.bulbagarden.net/wiki/Size_and_weight_variation#Generation_IX

> Pokémon come in several size groups, and their scale can be judged by a Hiker next to the West Mesagoza Pokémon Center. If the player shows off a Pokemon with a scale of 255 or 0, the Hiker will give that Pokémon a Jumbo or Mini Mark, respectively.
