### ISSUE TITLE
Shiny Gimmighoul from event raid PID mismatch?

### ISSUE THREAD

**Issue by arthurlee13** [MewTracker/sv-research#20]
When I try to input the PID and other parameters generated from RaidCalc to PKHex, it does not give me a shiny tag.
While I open some shiny gimmighoul .pk9 files from discord and search the corrisponding ones from RaidCalc, I found that the PID was different for the initial 4 digits, while the last 4 are the same (e.g. DF0A84C2 vs F46984C2).

**Comment by MewTracker** [comment]
That's normal. When game generates a raid it uses fake TID/SID value. When you capture raid Pokémon game will adjust its PID to maintain correct shininess based on your real TID/SID. This is essentially a TID/SID change and I described how this procedure works here: https://projectpokemon.org/home/forums/topic/62733-sv-raidcalc-seed-generator-for-injection-drop-farming-and-shinies/#comment-280976
