### ISSUE TITLE
Feature request / Item Drops

### ISSUE THREAD

**Issue by brianomatic1** [MewTracker/sv-research#21]
Terrafinder has these but your application does not:

Enigma berry
Micle Berry
Custap Berry
Jaboca Berry
Rowap Berry
Kee Berry
Maranga Berry

**Comment by MewTracker** [comment]
Options for filters are generated automatically from reward tables. If something cannot be obtained from Tera Raid, it's not available as an option. Do you have any example of a raid seed/parameters that provides such rewards? As far as I remember some rare berries like enigma berry aren't obtainable in SV in general (except for HOME trades).
