### ISSUE TITLE
Unable to find any seed result with new event

### ISSUE THREAD

**Issue by maxwell-zeus** [MewTracker/sv-research#23]
After the recent update, I can't seem to find any result even with basic filters such as blissey, normal tera, non shiny. I am sure that I have selected the correct drop down under events as well as selected 5 star raids. I event tried searching for both Event 1 and 2 parameters but the software always returns 0 seeds.

**Comment by maxwell-zeus** [comment]
![image](https://github.com/MewTracker/sv-research/assets/130150037/287984cb-e7a6-43c3-84d9-6f26fb0bcb73)

**Comment by maxwell-zeus** [comment]
Hi, i manage to pull some seeds by just limiting to 6IVs. Now my concern is, how can I search for the event TMs since it isn't found in the list of the TMs under filter.

TM 88 Swords Dance

**Comment by MewTracker** [comment]
Blissey is 5* raid in group 2. Swords Dance is available on filter's list as `TM88`.

Only Scizor and Hydreigon can drop it: https://www.serebii.net/scarletviolet/teraraidbattles/event-preparetheoffense.shtml
