### ISSUE TITLE
Crashing when looking for Iron Leaves Seeds

### ISSUE THREAD

**Issue by Lucas-Rosenzweig** [MewTracker/sv-research#24]
Here are the settings i used :

![image](https://github.com/MewTracker/sv-research/assets/38187137/ce985951-e899-479a-be8a-81873e63269a)

**Comment by MewTracker** [comment]
You are searching for something that is extremely common and you run out of memory to store all the results (after few seconds you already need over 25 GB). Make your criteria more restrictive or reduce seed search space.

**Comment by Xeit0w** [comment]
anks for the answer I wasn't sure I was doing things right, sorry for the inconvenience I'm closing the issue

**Comment by Lucas-Rosenzweig** [comment]
Tanks for the answer I wasn't sure I was doing things right, sorry for the inconvenience I'm closing the issue
