### ISSUE TITLE
DLC Raid Seeds

### ISSUE THREAD

**Issue by evilsneasel** [MewTracker/sv-research#25]
Great work on creating and maintaining this program.  Is there going to be an update to add the DLC raids seeds in the near future?

**Comment by MewTracker** [comment]
Sure, but I'm so busy at the moment I didn't even play the DLC yet 😅 This will take some time but I will add DLC support as soon as possible.

**Comment by evilsneasel** [comment]
Please don't rush yourself to get the support out.  Your IRL stuff should always come before updating a program for a game.

Great work on making and maintaining the program
