### ISSUE TITLE
Kitakami seeds

### ISSUE THREAD

**Issue by rayyano0o0** [MewTracker/sv-research#26]
First of all thank you very much for this amazing neat program i appreciate it

i would like to report that some of the Kitakami seeds doesn't show using the search option like Basculin in the data base its there in the kitakami map Scarlet game 3 Stars, when i use the search option it shows 0 seeds along with others but this is just an example.

**Comment by MewTracker** [comment]
Kitakami Pokémon with special forms are not properly supported in v5.0.0. This issue should be limited to:

- Basculin
- Basculegion
- Sinistcha

I will fix this in v5.1.0.
