### ISSUE TITLE
Size filters on events

### ISSUE THREAD

**Issue by jstrong17** [MewTracker/sv-research#28]
For the recently added of size filtering on 7* raids, you're only able to search 10MM seeds at once despite having far less results than this.

When searching filters for non-events, you're able to search all seeds (if there are under 10MM results).

RESOLUTION: Allow for the ability to search more than 10MM event seeds as long as there is less than 10MM results as you are able to do with non-event searches.

PICTURE 1: Shows searching 10MM seeds with 595 results.
![10MM event](https://github.com/MewTracker/sv-research/assets/153560960/6c229ba5-9eb2-49c8-bfc9-48741c0aa735)

PICTURE 2: Shows searching 10MM + 1 seeds with an error that the max results is more than 10MM (although the most it could be is 596 results).
![10MM plus 1 event](https://github.com/MewTracker/sv-research/assets/153560960/f19c587b-f49e-49c4-a4c3-86bc7ef7f815)

PICTURE 3: Shows searching every available seed (with no event) and finding 257,842 matching seeds.
![all seeds regular](https://github.com/MewTracker/sv-research/assets/153560960/cc631b97-3e78-4cf0-9ced-2f874b898ab7)

**Comment by MewTracker** [comment]
Nice catch. Fixed in cae7c067d0eb84ba870a4bba8cfbd8a5397d5d58
