### ISSUE TITLE
XP Candies

### ISSUE THREAD

**Issue by zerasemporium** [MewTracker/sv-research#3]
Hi there! 

What's the max XP candy you can get in a raid? 
Is there a way to get a raid with a lot of candy? like 5XL, 5L, 5 Normal? 

Still using your seeds every day for our community, thank you so much!

**Comment by MewTracker** [comment]
Sure:
1. Download the newest [RaidCalc](https://github.com/MewTracker/sv-research/releases)
1. Check `Activate Filters` in `Item Filters` group
1. Set `Min items sum` to 19
1. Press `Edit Filters`
1. Check `Exp. Candy M`,  `Exp. Candy L` and `Exp. Candy XL`
1. Close filters window
1. Press `Find Seeds`

You will get raids with 19-22 candies :)

**Comment by zerasemporium** [comment]
Oh wow, thank you!
