### ISSUE TITLE
Basculin red

### ISSUE THREAD

**Issue by rayyano0o0** [MewTracker/sv-research#33]
Hello, i would like to point out Basculin red is not available only white.

**Comment by MewTracker** [comment]
We don't provide filters for unobtainable forms.

**Comment by rayyano0o0** [comment]
my bad i thought it is available because you can find its info here !
![basculin 3 stars tera finder](https://github.com/user-attachments/assets/d4db5858-84b3-4b92-8eed-6afc0bc19bf3)
![basculin 3 stars](https://github.com/user-attachments/assets/04a92042-6f8e-4651-9e59-e0eaa63020ab)

https://bulbapedia.bulbagarden.net/wiki/List_of_3%E2%98%85_Tera_Raid_Battles_(Paldea)#Basculin

**Comment by MewTracker** [comment]
Indeed it seems that Red and White are obtainable now (Blue remains unobtainable). This must have changed as I'm pretty sure that wasn't the case before Kitakami patch. I will fix this in the next version.
