### ISSUE TITLE
Sinistea Forms

### ISSUE THREAD

**Issue by Falinkx** [MewTracker/sv-research#6]
Hello, first of all, what you're doing is great! Please keep it up, I really love RaidCalc.

This is not really an issue, more like a request. But I just wanted to ask since you added a filter by forms, can you also add the forms for Sinistea? Not sure if its possible, just thought I ask. The forms are Phony and Antique.

**Comment by MewTracker** [comment]
It wasn't added because Antique form cannot be obtained from tera raids.
