### ISSUE TITLE
1-4 star raid seeds

### ISSUE THREAD

**Issue by Falinkx** [MewTracker/sv-research#8]
Hello, I'm having issues injecting 1-3 star raid seeds. For example, a 3-star Shiny Indeedee raid seed, as soon as I inject it in the game using base05, I get a Avalugg 5-star raid (I'm doing a seed lookup using the correct game verions). I'm most likely doing it wrong that's why I'm here looking for some guidance. When injecting the raid seed, the only option we have is Black6, Base5, Distribution and Might7. Should I be injecting 1-4 star raid seed using base05? Or should it be Distribution? Or is the low star raid seeds not injectable? I appreciate your response. Thank you.

**Comment by MewTracker** [comment]
I suspect you might have wrong game progression settings. Remember that some raids become unavailable as you progress through the game (e.g. 1-2 star raids are no longer available after unlocking 5 star raids).

If you still have issues please give me exact settings and seed used, so I can verify it on my end.

> Should I be injecting 1-4 star raid seed using base05?

Yes.

**Comment by Falinkx** [comment]
I appreciate your response. That must be it, I'm injecting a 1-2star raid in a save with 6-star raids unlocked. I will try this out on a save that have not unlocked the 5-star raids yet and will keep you posted if it works or not. Thank you.

**Comment by MewTracker** [comment]
Please note that RaidCalc will not allow you to select impossible combinations. Example:
- Story progress: 6* unlocked
- Stars: 6

If you try to change stars to 2, RaidCalc will automatically adjust story progress to "None". This will be signalled with a beep sound. Same goes for story progress adjustment, it can automatically adjust stars if necessary.

**Comment by Falinkx** [comment]
Can confirm its working, as long as your save has not unlocked the 5star raids yet. Thanks.
