### ISSUE TITLE
Indeedee Tera Raid - Female

### ISSUE THREAD

**Issue by Falinkx** [MewTracker/sv-research#9]
Hello,

Just checking to see if there are no raid seeds for female indeedee? So far all indeedee raids are male. I tried with the following settings:

Story Progress: 6* Unlocked
Stars: 3*
Shiny: Any

And with this settings:
Story Progress: 3* Unlocked
Stars: 3*
Shiny: Any

**Comment by MewTracker** [comment]
I confirm this is a bug introduced in v3.2.0 due to form filtering. Indeedee male and female are considered separate forms and RaidCalc is not aware of this, so it searches for primary (male) form only.

I will fix this soon. Meanwhile you can use v3.1.0 that works properly.
